spring:
  application:
    name: ems

  datasource:
    url: jdbc:mysql://localhost:3307/skyllx_db
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true